all:
	gcc -Wall -Werror -Wextra -std=c99 linked_list.c && ./a.out

list:
	gcc -Wall -Werror -Wextra -std=c99 linked_list.c linked_list_tester.c && ./a.out

linprog:
	gcc -Wall -Werror -Wextra -std=c99 linked_list.c linear_program.c && ./a.out



